name: Scrape Letterboxd

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scrape_letterboxd.py

      - name: Check git status before commit
        run: |
          git status
          git diff
          git diff --name-only

      - name: Commit scraped data if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git diff --cached --quiet || (
            git commit -m "Update scraped data"
            git push
          )
        shell: bash

      - name: Upload scrape output files as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scrape-results
          path: |
            debug.html
            latest_films.json
