name: Scrape Letterboxd

on:
  schedule:
    - cron: "0 3 * * *" # Runs daily at 03:00 UTC
  workflow_dispatch: # allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run scraper
        run: python scrape_letterboxd.py

      - name: Commit and push if data changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add latest_films.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update scraped data"
          git push
