name: Scrape Letterboxd and Deploy JSON

on:
  schedule:
    - cron: "0 0 * * *"   # daily at midnight UTC
  workflow_dispatch:       # manual trigger

jobs:
  scrape-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout scraper repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scrape_letterboxd.py

      - name: Configure git for pushing
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Clone GitHub Pages repo
        env:
          GH_PAGES_PAT: ${{ secrets.GH_PAGES_PAT }}
        run: |
          git clone https://x-access-token:${GH_PAGES_PAT}@github.com/ptb-im/ptb-im.github.io.git pages

      - name: Copy latest_films.json to GitHub Pages repo
        run: |
          cp latest_films.json pages/
          cd pages
          git add latest_films.json
          git diff --cached --quiet || (
            git commit -m "Update latest films JSON from scraper"
            git push origin main
          )
